export { default as logo } from "./logo.png"
export { default as profile1 } from "./profile-1.png"
export { default as profile3 } from "./profile-2.png"
// export { default as profile2 } from "./profile-2.JPG"
// export { default as profile3 } from "./profile-3.jpeg"
// export { default as profile4 } from "./profile-4.jpeg"
// export { default as profile5 } from "./profile-5.jpeg"
// export { default as profile6 } from "./profile-6.jpeg"
export { default as project1 } from "./projectsImg/project-1.PNG"
export { default as project2 } from "./projectsImg/project-2.PNG"
export { default as project3 } from "./projectsImg/project-3.PNG"
export { default as project4 } from "./projectsImg/project-4.PNG"
export { default as project5 } from "./projectsImg/project-5.PNG"
export { default as project6 } from "./projectsImg/project-6.PNG"
export { default as project7 } from "./projectsImg/project-7.PNG"
export { default as project8 } from "./projectsImg/project-8.PNG"
